#!/usr/bin/env bash
# TheMengzor/gist:968e5ea87e99d9c41782
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
# TheMengzor/gist:968e5ea87e99d9c41782

BASE_DIR="$(dirname $DIR)"
PKG_NAME=$(basename $BASE_DIR)
CONTAINER_DIR=$(dirname $BASE_DIR)
APP_DIR=$(dirname $CONTAINER_DIR)

if [ $(basename $CONTAINER_DIR) == "node_modules" ] && [ -d $APP_DIR/es/modules ]; then
  rm $APP_DIR/es/modules/$PKG_NAME
fi
